version: '3.8'
services:
  config-service:
    build:
      context: ./config-service
      dockerfile: Dockerfile
    container_name: config-service
    networks:
      - msa-network
    ports:
      - "8888:8888"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://config-service:8888/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    networks:
      - msa-network
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://discovery-service:8761" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  gateway-service:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    container_name: gateway-service
    networks:
      - msa-network
    ports:
      - "8000:8000"
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    container_name: user-service
    networks:
      - msa-network
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  order-service:
    build:
      context: ./ordering-service
      dockerfile: Dockerfile
    container_name: order-service
    networks:
      - msa-network
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8081/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  product-service:
    build:
      context: ./product-service
      dockerfile: Dockerfile
    container_name: product-service
    networks:
      - msa-network
    depends_on:
      discovery-service:
        condition: service_healthy
      config-service:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8082/actuator/health" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - msa-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

  mysql-db:
    image: mysql:8
    ports:
      - "3316:3306"
    networks:
      - msa-network
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: orderservice
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 30s
    restart: always

networks:
  msa-network:
    driver: bridge

volumes:
  db-data:
