# 서비스 변경 감지용 주석

server:
  port: 0

spring:
  application:
    name: user-service

  mail:
    host: smtp.gmail.com # SMTP 서버 호스트
    port: 587 # SMTP 서버 포트
    username: hjk326333
    password:  # 앱 비밀번호 16자리 (공백없이)
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true













