apiVersion: v1
kind: Service
metadata:
  name: pr
spec:
  selector:
    app: ordering-service
  ports:
    - protocol: TCP
      port: {{ .Values.port}}
      targetPort: {{ .Values.port }}
  type: NodePort